<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginTaggingTable extends Doctrine_Table
{
  public $subclasses  =  array();
  
  public function setTableDefinition() {
    $this->option('export', 'tables');
    
    $this->setSubClasses($this->subclasses); 
      
  }
  
  public function setUp() {
    echo 'hai vom PluginTaggingTable';
  }
  
  public function addSubclass($map) {
    $subclasses = $this->subclasses;
    $this->subclasses = array_merge($subclasses, $map);
  }

}